global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
      
  - job_name: 'dialog-service'
    static_configs:
      - targets: ['dialog-service:8080']