{
 "title": "Example Performance Dashboard",
 "tags": [ "example" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_request_duration_seconds_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{job=\"$job\",instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Successful Requests (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(rate(http_requests_received_total{job=\"$job\",instance=\"$instance\",code=~\"2..\"}[5m])) / sum(rate(http_requests_received_total{job=\"$job\",instance=\"$instance\"}[5m])))*100)"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"$job\",instance=\"$instance\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Usage (process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "DB Query Duration (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(npgsql_db_client_commands_duration_bucket{job=\"$job\",instance=\"$instance\"}[5m])))"
    }
   ]
  },
  {
   "title": "currentRequests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "totalRequests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error Requests (4xx,5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{job=\"$job\",instance=\"$instance\",code=~\"4..|5..\"})"
    }
   ]
  }
 ]
}